config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'

  resources :graphs, extend: %i[new edit] do
    resources :nodes, :arcs, shallow: true, only: %i[update]
    resources :nodes, :arcs, only: :create
    collection do
      get :get_graphs
      post :calcul_cartesian_product
      post :calcul_vector_product
      get :autocomplete
      get :open
      get :close
    end
    member do
      post :clipboard_data
      post :copy_to_clipboard
      post :find_hamiltonyan_cycles
      post :to_full
      post :update_elements
      post :selected_elements
      post :delete_elements
    end
  end
end

app/models/graph.rb
class Graph < ApplicationRecord
  has_many :nodes, dependent: :destroy
  has_many :arcs, dependent: :destroy

  validates :name,
            presence: true,
            uniqueness: true,
            format: /\A((?!New graph \d).)*\z/,
            on: :update

  searchkick
  def search_data
    {
      name: name
    }
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :find_graph, extend: %i[create autocomplete open calcul_cartesian_product calcul_vector_product]
  respond_to :js

  def index
    @graphs = Graph.all.map { |graph| [graph.name, graph.id] }
    @path = "/graphs/calcul_#{params[:product]}_product"
  end

  def create
    @graph = Graph.create
    @graph.name = new_graph_name(@graph.id)
    @graph.save(validate: false)
    calcul_qualities
  end

  def update
    head :no_content unless @graph.update(params.require(:graph).permit(:name))
  end

  def show
    calcul_qualities
  end

  def destroy
    @graph.destroy
  end

  def autocomplete
    render json: Graph.search(params[:name],
                              {
                                limit: 10,
                                load: false,
                                misspellings: { below: 3 }
                              }).map(&:name)
  end

  def open
    @graph = Graph.find_by(name: params[:name])
    calcul_qualities if @graph
    render 'create' if @graph
  end

  def close
    render 'destroy'
  end

  def copy_to_clipboard
    session[:clipboard] = params[:selected]
    head :no_content
  end

  def clipboard_data
    if session[:clipboard]
      session[:clipboard]['nodes'].each do |num_hash|
        node = num_hash.last
        @graph.nodes.create(name: node['id'], x: node['x'].to_i, y: node['y'].to_i, color: node['color'])
      end
      session[:clipboard]['arcs']&.each do |num_hash|
        arc = num_hash.last
        if (start_node = @graph.nodes.find_by(name: arc['start_id'])) && (finish_node = @graph.nodes.find_by(name: arc['finish_id']))
          @graph.arcs.create(start_node: start_node, finish_node: finish_node, color: arc['color'], arc_type: arc['arc_type'])
        end
      end
      session[:clipboard]['nodes'].each do |num_hash|
        node = num_hash.last
        @graph.nodes.find_by(name: node['id']).update(name: node['name'])
      end
      calcul_qualities
    end
    render 'show'
  end

  def to_full
    arcs = @graph.arcs
    nodes = @graph.nodes
    matrix = GraphService.get_adjacency_matrix(nodes, arcs)
    arcs.each do |arc|
      arc.update(arc_type: 'common')
    end
    nodes.length.times do |start_node|
      nodes.length.times do |finish_node|
        unless GraphService.adjacency_nodes?(matrix, start_node, finish_node)
          @graph.arcs.create(start_node: nodes[start_node], finish_node: nodes[finish_node], arc_type: 'common') if start_node != finish_node
        end
      end
    end
    render 'show_ajax'
  end

  def find_hamiltonyan_cycles
    @cycles = GraphService.find_hamiltonyan_cycles(@graph)
    @string_cycles = []
    nodes = @graph.nodes
    @cycles.each do |cycle|
      string = ''
      cycle.each do |node_index|
        string += " => #{nodes[node_index].name} (#{nodes[node_index].id})"
      end
      @string_cycles.push(string)
    end
  end

  def calcul_cartesian_product
    @graph1 = Graph.find_by(id: params[:first_graph_id])
    @graph2 = Graph.find_by(id: params[:second_graph_id])
    cartesian_matrix = GraphService.cartesian_product_matrix(@graph1, @graph2)
    @graph = create_graph_by_matrix(cartesian_matrix)
    calcul_qualities
    render 'create'
  end

  def calcul_vector_product
    @graph1 = Graph.find_by(id: params[:first_graph_id])
    @graph2 = Graph.find_by(id: params[:second_graph_id])
    vector_matrix = GraphService.vector_product_matrix(@graph1, @graph2)
    @graph = create_graph_by_matrix(vector_matrix)
    calcul_qualities
    render 'create'
  end

  def selected_elements
    @nodes = JSON.parse(params[:nodes]) if params[:nodes]
    @arcs = JSON.parse(params[:arcs]) if params[:arcs]
  end

  def update_elements
    find_node(params[:nodes].first).update(name: node_params) if node_params
    find_arc(params[:arcs].first).update(arc_type: arc_params) if arc_params
    params[:nodes]&.map { |id| find_node(id).update(color: params[:color]) }
    params[:arcs]&.map { |id| find_arc(id).update(color: params[:color]) }
  end

  def delete_elements
    params[:nodes]&.map { |id| find_node(id).destroy }
    params[:arcs]&.map { |id| find_arc(id)&.destroy }
    render 'show_ajax'
  end

  private

  def create_graph_by_matrix(matrix)
    start_x = 200
    start_y = 200
    graph = Graph.create
    graph.name = new_graph_name(graph.id)
    graph.save(validate: false)
    matrix.length.times do |t|
      graph.nodes.create(x: start_x, y: start_y, name: "node #{t + 1}")
      start_x < 800 ? start_x += 100 : start_x -= 100
      start_y < 600 ? start_y += 50 : start_y -= 50
    end
    nodes = graph.nodes
    matrix.length.times do |i|
      matrix.length.times do |j|
        if matrix[i][j] == 1
          if arc = graph.arcs.find_by(start_node: nodes[j], finish_node: nodes[i])
            arc.update(arc_type: 'common')
          else
            graph.arcs.create(arc_type: 'oriented', start_node: nodes[i], finish_node: nodes[j])
          end
        end
      end
    end
    graph
  end

  def node_params
    params[:name]
  end

  def calcul_qualities
    @matrix = GraphService.get_adjacency_matrix(@graph.nodes, @graph.arcs)
    eccentricities = GraphService.find_eccentricities(@matrix)
    @radius = GraphService.get_radius(eccentricities)
    @diameter = GraphService.get_diameter(eccentricities)
    @center = GraphService.get_center(eccentricities, @graph.nodes)
    @full_graph = GraphService.full?(@matrix)
  end

  def arc_params
    params[:arc_type]
  end

  def find_node(id)
    Node.find_by(id: id)
  end

  def find_arc(id)
    Arc.find_by(id: id)
  end

  def new_graph_name(id)
    "New graph #{id}"
  end

  def find_graph
    @graph = Graph.find_by(id: params[:id])
  end
end

app/helpers/graph_helper.rb
module GraphHelper
  def unique_node?
    return false unless check_elements?

    @nodes.length == 1 && @arcs.length.zero? ? true : false
  end

  def unique_arc?
    return false unless check_elements?

    @nodes.length.zero? && @arcs.length == 1 ? true : false
  end

  def color
    colors = (@nodes + @arcs).map { |object| object['color'] }
    colors.uniq.length > 1 ? '#000000' : colors.first
  end

  def nodes_id
    @nodes.map { |node| node['id'] }
  end

  def arcs_id
    @arcs.map { |arc| arc['id'] }
  end

  private

  def check_elements?
    @nodes && @arcs ? true : false
  end
end

app/helpers/graphs_helper.rb
module GraphsHelper
  include NodesHelper
  def unique_node?
    special_length?(arcs: 0, nodes: 1)
  end

  def unique_arc?
    special_length?(arcs: 1, nodes: 0)
  end

  def any_elements?
    @nodes.length.positive? || @arcs.length.positive?
  end

  def special_length?(arcs:, nodes:)
    return false unless check_elements?

    @nodes.length == nodes && @arcs.length == arcs
  end

  def color
    colors = (@nodes + @arcs).map { |object| object['color'] }
    colors.uniq.length > 1 ? '#000000' : colors.first
  end

  def nodes_id
    @nodes.map { |node| node['id'] }
  end

  def arcs_id
    @arcs.map { |arc| arc['id'] }
  end

  def check_elements?
    @nodes && @arcs
  end
end

app/views/graphs/_adjacency_table.html.slim
#adjacencyTable
  .card
    #headingOne.card-header
      h2.mb-0.text-center
        button.btn.btn-light.btn-lg type="button" data-toggle="collapse" data-target="#Collapse" aria-expanded="true" aria-controls="Collapse"
          | Show adjacency table
    #Collapse.collapse.hide  aria-labelledby="headingOne" data-parent="#adjacencyTable"
      .card-body
          table.table.table-bordered
            thead
              tr
                th scope="col" adjacency table
                - @graph.nodes.select(:name, :id).each do |node|
                  th scope="col"  = "#{node.name} (#{node.id})"
            tbody
              - @graph.nodes.count.times do |index|
                tr
                  th scope="row" 
                    = "#{@graph.nodes[index].name} (#{@graph.nodes[index].id})"
                    - @matrix[index].each do |elem|
                      td = elem

app/views/graphs/_graph_info.html.slim
#graph_info
  - if @graph.nodes.length > 0
    h3.mt-3.text-center Graph info
    h4.mt-4 = "Full: #{@full_graph}" 
    h4.mt-4 = "Radius: #{@radius}"
    h4.mt-4 = "Diameter: #{@diameter}"
    h4.mt-4 Center:
    ul.list-group
      - @center.each do |node|
        li.list-group-item = "#{node.name} (#{node.id})"

app/views/graphs/_hamiltonyan_cycles_modal.html.slim
.modal.fade aria-hidden="true" id="hamiltonyanCycles" aria-labelledby="HamiltonyanCycles" role="dialog" tabindex="-1" 
  .modal-dialog.modal-dialog-centered role="document" 
    .modal-content
      .modal-header
        h5#exampleModalCenterTitle.modal-title Hamiltonyan cycles
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
      .modal-body
      ul.list-group  
        - @string_cycles.each do |cycle|
          li.list-group-item
            = cycle.slice(3..cycle.length)

app/views/graphs/_rename_graph_modal.html.slim
.modal.fade aria-hidden="true" id="renameGraph#{@graph.id}Modal" aria-labelledby="exampleModalCenterTitle" role="dialog" tabindex="-1" 
  .modal-dialog.modal-dialog-centered role="document" 
    .modal-content
      .modal-header
        h5#exampleModalCenterTitle.modal-title Change name of graph
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
      .modal-body
        = form_with model: @graph, method: :put do |f|
          = f.text_field :name, class: "form-control", require: true
          .modal-footer
            button.btn.btn-secondary data-dismiss="modal" type="button"  Close
            = f.submit "Save Changes", class: "btn btn-primary"

app/views/graphs/_update_modal.html.slim
.modal aria-hidden="true" id="updateElementsModal" aria-labelledby="exampleModalCenterTitle" role="dialog" tabindex="-1" 
  .modal-dialog.modal-dialog-centered role="document" 
    .modal-content
      .modal-header
        h5#exampleModalCenterTitle.modal-title Update elements
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
      .modal-body
        = form_with url: update_elements_graph_path(@graph.id, nodes: nodes_id, arcs: arcs_id), class: 'form-inline' do |f|
          - if unique_node?
            .form-group.mb-3.w-50
              = f.label :name, "Node name"
              = f.text_field :name, class: "form-control w-75", value: @nodes.first['name'], require: true
          - if unique_arc?
            .form-group.mb-3.w-50
              = f.label :arc_type, "Type"
              = f.select :arc_type,  options_for_select(['common', 'oriented'], @arcs.first['arc_type']), { require: true }, { class: "form-control w-100" }
          .form-group.mb-3.w-50
            = f.label :color, 'Color'
            = f.color_field :color, class: 'form-control w-100', value: color
          .modal-footer
            button.btn.btn-secondary data-dismiss="modal" type="button"  Close
            = f.submit "Save Changes", id:'submitUpdates', class: "btn btn-primary"

app/views/graphs/create.html.slim
li.nav-item.form.row.ml-0.mr-0 id="graph-#{@graph.id}"
    = render partial: 'rename_graph_modal'
    a.nav-link.active[data-toggle="tab" title="Double click to change name" href="##{@graph.id}" role="tab" aria-selected="true" id="link-#{@graph.id.to_s}"]
      | #{@graph.name}
    = link_to "✕", close_graphs_path(id: @graph.id), class:"badge badge-danger cross-delete-text", title:"Delete graph", methdd: 'get', remote: :true
    javascript:
      $('#link-' + "#{@graph.id}").click(function(e) {
        e.preventDefault();
        $.ajax({
          url: 'graphs/' + "#{@graph.id}",
          type: "GET",
          processData: false,
          contentType: false
        })
      });

app/views/graphs/destroy.js.slim
| $('#graph-#{@graph.id}').remove();
| $('#graphFunctions').replaceWith('<ul id="graphFunctions" class="navbar-nav"></ul>');
| $('.tools-bar ul').replaceWith('<ul id="tools-bar"></ul>');
| $('#working_area').replaceWith('<div id="working_area"></div>');
| $('#graph_info').replaceWith('<div id="graph_info"></div>');
| $('#adjacencyTable').replaceWith('<div id="adjacencyTable"></div>');

app/views/graphs/find_hamiltonyan_cycles.js.slim
| $('#hamiltonyanCycles').replaceWith('
= j render partial: 'graphs/hamiltonyan_cycles_modal'
| ');
| $('#hamiltonyanCycles').modal('show');

app/views/graphs/index.js.slim
| $('#choosingGraphs').replaceWith('
= j render partial: 'graphs/choosing_graphs_for_product_modal.html.slim'
| ');
| $('#choosingGraphs').modal('show');

app/views/graphs/selected_elements.js.slim
| $('#tools-bar').replaceWith('
= j render partial: 'application/tools_bar.html.slim'
| ');
| $('#updateElementsModal').replaceWith('
= j render partial: 'graphs/update_modal.html.slim'
| ');

app/views/graphs/show.js.slim
| $('#graphFunctions').replaceWith('
= j render template: 'graphs/functions'
| ');
| $('#tools-bar').replaceWith('
= j render partial: 'application/tools_bar.html.slim'
| ');
| $('#working_area').replaceWith('
= j render partial: 'application/working_area.html.slim'
| ');
| $('#graph_info').replaceWith('
= j render partial: 'graphs/graph_info'
| ');
| $('#adjacencyTable').replaceWith('
= j render partial: 'graphs/adjacency_table'
| ');

app/views/graphs/show_ajax.js.slim
| $.ajax({
    url: "#{graph_path(@graph)}"
  })

app/views/graphs/update.js.slim
| $(function(){
  $('#renameGraph#{@graph.id}Modal').modal('hide');
  var newName = $("#renameGraph#{@graph.id}Modal #graph_name").val();
  $("#graph-#{@graph.id} a[role='tab']").text(newName);
| }); 

app/views/graphs/update_elements.js.slim
| $('#updateElementsModal').modal('hide');
= render template: 'graphs/show_ajax.js.slim' 