config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'

  resources :graphs, extend: %i[new edit] do
    resources :nodes, :arcs, shallow: true, only: %i[update]
    resources :nodes, :arcs, only: :create
    collection do
      get :get_graphs
      post :calcul_cartesian_product
      post :calcul_vector_product
      get :autocomplete
      get :open
      get :close
    end
    member do
      post :clipboard_data
      post :copy_to_clipboard
      post :find_hamiltonyan_cycles
      post :to_full
      post :update_elements
      post :selected_elements
      post :delete_elements
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
  include GraphsHelper
end

app/views/application/_MDI.html.slim
ul class="nav nav-tabs" id="graphs"

app/views/application/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.header style="background-color: #44007e;"
    a.navbar-brand href="#"  GraphEditor
    button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav
        li.nav-item.active.m-auto
            = link_to "New graph", graphs_path, class:"nav-link active", method: :post, remote: :true
            span.sr-only (current)
        = form_with url: open_graphs_path, class: 'form-inline', method: 'get' do |f|
          li.nav-item.active.ml-5.mr-3
            = f.submit "Open", class:"btn btn-outline-warning" 
          li.nav-item.m-auto
            = f.text_field :name, id: 'graph_name', placeholder: 'Find graph', class: 'form-control'
            javascript:
              var graphs = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.whitespace,
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                  url: '/graphs/autocomplete?name=%QUERY',
                  wildcard: '%QUERY'
                }
              });
              $('#graph_name').typeahead({
                  highlight: true,
                  hint: true,
                  minLength: 1
              },
              {
                source: graphs
              });
      ul#graphFunctions.navbar-nav

app/views/application/_tools_bar.html.slim
ul#tools-bar.nav.flex-column
  li.nav-item
    = link_to image_tag('add_node_icon.png', size: '35x35'),
              graph_nodes_path(@graph.id),
              class: 'btn btn-light',
              title: 'Create node',
              method: :post,
              remote: true
  - if check_elements?
    - if unique_node? || special_length?(arcs: 0, nodes: 2)
      li.nav-item
        = link_to image_tag('add_common_arc_icon.png', size: '35x35'),
                  graph_arcs_path(@graph.id, arc_type: 'common', start_node_id: nodes_id.first, finish_node_id: nodes_id.last),
                  method: :post,
                  title: 'Create common arc',
                  class: 'btn btn-light',
                  remote: true
      li.nav-item
        = link_to image_tag('add_oriented_arc_icon.png', size: '35x35'),
                  graph_arcs_path(@graph.id, arc_type: 'oriented', start_node_id: nodes_id.first, finish_node_id: nodes_id.last),
                  method: :post,
                  title: 'Create oriented arc',
                  class: 'btn btn-light',
                  remote: true
    - if any_elements?
      li.nav-item
        = render 'update_modal'
        a.btn.btn-light[id="updateElementsLink" title='Update elements']
          = image_tag 'update_elements_icon.png', size: '35x35'
        javascript:
          $('#updateElementsLink').click(function() {
            $('#updateElementsModal').modal('show');
          });
      li.nav-item
        = link_to image_tag('delete_elements_icon.png', size: '35x35'),
                  delete_elements_graph_path(@graph.id, nodes: nodes_id, arcs: arcs_id),
                  method: :post,
                  class: 'btn btn-light',
                  title: 'Delete elements',
                  data: { confirm: "Are you sure?" },
                  remote: true

app/views/application/_working_area.html.slim
#working_area.form-row tabIndex='0'
  .canvas.md-11.w-100
    = react_component('CanvasArea', render(template: 'graphs/show.json'))
    javascript:
      ReactRailsUJS.mountComponents()

app/views/application/index.html.slim
.global-space.row.mr-0.h-80
  .working-area.col-md-8.row
    .graph-area.col-md-11
      = render 'MDI'
      #working_area
    .tools-bar.col-md-1.mt-5
      ul#tools-bar
  .graphInfo.col.md-4
    #graph_info
#adjacencyTable